# VENDORED FROM pydcs (dcs-retribution/pydcs @ 3a79b8ed, 2026-07-25),
# UNMODIFIED. LGPL-3.0 — see vendor/dcs/COPYING.LESSER.
#
# Our own probe-derived projection, which this replaces, agreed with it to
# 2.3e-5 m on false_easting and 3.8e-5 m on false_northing — same central
# meridian, same scale factor. The 'provisional' label on ours turned out
# to be over-cautious, not wrong.
# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=63,
    false_easting=-300149.9999999864,
    false_northing=-3759657.000000049,
    scale_factor=0.9996,
)
