# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=45,
    false_easting=72290.00000004497,
    false_northing=-3680057.0,
    scale_factor=0.9996,
)
