#!/usr/bin/env python3
"""Generate the Flightline token CSS inside frontend/index.html.

THE anti-fork mechanism for the site (plan §2): the site's colors and fonts
are written by this script from `missiongen/data/brand/flightline.json` — the
same token file the kneeboard, brief and guide read — into a marked block in
the frontend. Registered in scripts/artifacts.py with a REBUILD rule, so
preflight fails if anyone hand-edits a color inside the markers or changes
the token file without regenerating.

Two modes, one set of variable NAMES. The whole 3,000-line stylesheet consumes
`--bg/--panel/--text/--accent/…`; the mode blocks re-value them. That is what
makes a full re-theme a surgical change instead of a rewrite: components keep
their names, `body[data-mode]` decides what the names mean.

Paper is the DEFAULT (Rob's call, plan §5): the kit's warm manual stock, navy
identity, flat surfaces. Night re-steps the same names onto the kit's
cockpit-adjacent palette — phosphor for good, instrument cyan for the
actionable accent (navy is invisible on near-black), the night warning/caution
pair for states.

Fonts are self-hosted from /fonts (see server/app.py) — the Google Fonts
<link> is gone, which also stops shipping every visitor's IP to a third party
the moment they open the page. The analytics stance ("no PII leaves") now
holds for fonts too.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
FRONTEND = ROOT / "frontend" / "index.html"
TOKENS = json.loads((ROOT / "missiongen" / "data" / "brand" /
                     "flightline.json").read_text())

BEGIN = "/* FLIGHTLINE:TOKENS:BEGIN — generated by scripts/gen_theme.py; do not edit by hand */"
END = "/* FLIGHTLINE:TOKENS:END */"

C = TOKENS["colors"]


def _fontface():
    faces = [
        ("Barlow Condensed", "BarlowCondensed-Bold.ttf", "700", None),
        ("Barlow Condensed", "BarlowCondensed-ExtraBold.ttf", "800", None),
        ("Bangers", "Bangers-Regular.ttf", "400", None),
        ("Source Sans 3", "SourceSans3-VF.ttf", "300 900", None),
        ("Source Serif 4", "SourceSerif4-VF.ttf", "300 900", None),
        ("IBM Plex Mono", "IBMPlexMono-Regular.ttf", "400", None),
        ("IBM Plex Mono", "IBMPlexMono-Medium.ttf", "500", None),
        ("IBM Plex Mono", "IBMPlexMono-SemiBold.ttf", "600", None),
        ("IBM Plex Mono", "IBMPlexMono-Bold.ttf", "700", None),
    ]
    out = []
    for fam, file, weight, style in faces:
        out.append(
            f"@font-face {{ font-family: '{fam}'; src: url('/fonts/{file}') "
            f"format('truetype'); font-weight: {weight}; "
            f"font-style: {style or 'normal'}; font-display: swap; }}")
    return "\n  ".join(out)


ROLE_NAMES = ("a2a", "strike", "sead", "cas", "carrier", "training", "historic")


def _roles(dark: bool) -> str:
    """The Library's role taxonomy — Apple system colors in their HIG
    ACCESSIBLE variants (role labels are 11px text; the default variants fail
    AA there). See _surface_note_3 in the token file for the full record."""
    sfx = "_dark" if dark else ""
    return " ".join(f"--{n}: {C[f'role_{n}{sfx}']};" for n in ROLE_NAMES)


def block() -> str:
    return f"""{BEGIN}
  {_fontface()}
  :root {{
    --font-display: 'Barlow Condensed', 'Arial Narrow', system-ui, sans-serif;
    --font-body: 'Source Sans 3', system-ui, sans-serif;
    --font-mono: 'IBM Plex Mono', ui-monospace, monospace;
    --font-banner: 'Bangers', 'Barlow Condensed', sans-serif;
    --radius: 10px;
    --shadow: none;
  }}
  /* LIGHT — Apple HIG system colors (Rob's spec, 12 Aug: "the Apple design
     guide for their applications, with the exception of the typography stack
     we're currently using"). Grouped background, white cards, hairline
     separators, systemBlue as THE accent, semantic red/orange/green. The one
     deviation from Apple's published values: secondary label darkened to
     #6E6E73 to hold WCAG AA on white (Apple's #8A8A8E is 3.0:1). Documents
     are untouched — HIG governs applications, not print. */
  body[data-mode="paper"] {{
    --bg: {C['sys_bg']}; --panel: {C['white']}; --panel2: {C['sys_fill']};
    --line: {C['sys_sep']}; --text: #000000; --dim: {C['sys_dim']};
    --accent: {C['sys_blue']}; --accent-hi: #339CFF; --accent-text: {C['white']};
    --accent-small: {C['sys_blue_access']}; --accent-solid: {C['sys_blue_access']};
    --green-small: {C['sys_green_access']};
    --green: {C['sys_green']}; --amber: {C['sys_orange']}; --warn: {C['sys_red']};
    --band: {C['white']}; --band-text: #000000; --band-dim: {C['sys_dim']};
    {_roles(dark=False)}
  }}
  /* DARK — Apple's dark system set: true-black ground, elevated dark panels,
     the dark variants of blue/green/orange/red. */
  body[data-mode="night"] {{
    --bg: {C['sys_dark_bg']}; --panel: {C['sys_dark_panel']}; --panel2: {C['sys_dark_fill']};
    --line: {C['sys_dark_sep']}; --text: {C['white']}; --dim: {C['sys_dark_dim']};
    --accent: {C['sys_blue_dark']}; --accent-hi: #409CFF; --accent-text: {C['white']};
    --accent-small: {C['sys_blue_access_dark']}; --accent-solid: {C['sys_blue_solid_dark']};
    --green-small: {C['sys_green_dark']};
    --green: {C['sys_green_dark']}; --amber: {C['sys_orange_dark']}; --warn: {C['sys_red_dark']};
    --band: {C['sys_dark_panel']}; --band-text: {C['white']}; --band-dim: {C['sys_dark_dim']};
    {_roles(dark=True)}
  }}
  {END}"""


def main(check=False):
    src = FRONTEND.read_text()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(src):
        sys.exit("gen_theme: markers not found in frontend/index.html")
    out = pat.sub(lambda _m: block(), src, count=1)
    if check:
        if out != src:
            sys.exit("gen_theme: frontend token block is STALE — run "
                     "scripts/gen_theme.py")
        print("gen_theme: token block is current")
        return
    FRONTEND.write_text(out)
    print("gen_theme: token block written")


if __name__ == "__main__":
    main(check="--check" in sys.argv)
